version: '3.1'

services:
  test-db:
    image: "postgres:13.4"
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: testDbUser
      POSTGRES_PASSWORD: testDbPassword
      POSTGRES_DB: testDb
    ports:
      - 5435:5432
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]